# Generated by Django 2.1.7 on 2021-08-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64, verbose_name='账号')),
                ('password', models.CharField(default='', max_length=64, verbose_name='密码')),
                ('cookie', models.TextField(default='', verbose_name='Cookie')),
            ],
        ),
        migrations.CreateModel(
            name='WebModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='网站名称')),
                ('loginurl', models.CharField(default='', max_length=255, verbose_name='登录网址')),
                ('indexurl', models.CharField(default='', max_length=255, verbose_name='首页网址')),
            ],
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cookie.WebModel', verbose_name='归属网站'),
        ),
    ]
