# Generated by Django 2.1.7 on 2021-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmodel',
            name='activate_js_script',
            field=models.TextField(default='', verbose_name='活跃Cookie的JS脚本'),
        ),
        migrations.AddField(
            model_name='webmodel',
            name='activate_python_script',
            field=models.TextField(default='', verbose_name='活跃Cookie的Python脚本'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='cookie',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Cookie'),
        ),
    ]
