# Generated by Django 2.1.7 on 2021-08-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0002_auto_20210803_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmodel',
            name='use_python_or_javascript_script',
            field=models.CharField(choices=[('python', 'python'), ('javascript', 'javascript')], default='python', max_length=64, verbose_name='选择使用脚本'),
        ),
    ]
