# Generated by Django 2.1.7 on 2021-08-03 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0003_webmodel_use_python_or_javascript_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opera', models.CharField(default='', max_length=128, verbose_name='操作')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_record', to='cookie.AccountModel', verbose_name='归属账号')),
            ],
        ),
        migrations.RemoveField(
            model_name='webmodel',
            name='activate_js_script',
        ),
        migrations.RemoveField(
            model_name='webmodel',
            name='activate_python_script',
        ),
        migrations.RemoveField(
            model_name='webmodel',
            name='use_python_or_javascript_script',
        ),
        migrations.AddField(
            model_name='webmodel',
            name='active_cookie_use_python_or_javascript_script',
            field=models.CharField(choices=[('python', 'python'), ('javascript', 'javascript'), ('default', 'default')], default='default', max_length=64, verbose_name='选择使用脚本'),
        ),
        migrations.AddField(
            model_name='webmodel',
            name='active_js_script',
            field=models.TextField(blank=True, default='', null=True, verbose_name='活跃Cookie的JS脚本'),
        ),
        migrations.AddField(
            model_name='webmodel',
            name='active_python_script',
            field=models.TextField(blank=True, default='', null=True, verbose_name='活跃Cookie的Python脚本'),
        ),
        migrations.AddField(
            model_name='webmodel',
            name='extract_cookie_script',
            field=models.TextField(blank=True, default='', null=True, verbose_name='提取Cookie的Python脚本'),
        ),
        migrations.AddField(
            model_name='webmodel',
            name='half_or_auto_get_cookie',
            field=models.CharField(choices=[('auto', 'auto'), ('half', 'half')], default='auto', max_length=32, verbose_name='全自动或半自动获取Cookie'),
        ),
    ]
