# Generated by Django 2.1.7 on 2021-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0006_accountmodel_opera_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmodel',
            name='wait_exec_active_js_script',
            field=models.IntegerField(default=100, verbose_name='等待JS执行的时间'),
        ),
    ]
